name: Build-Docs

on:
  push:
    branches:
      main


jobs:
  deploy_docs:
    name: Install fieldopt
    runs-on: ubuntu-latest
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Checkout code
      uses: actions/checkout@v2

    - name: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install package
      run: |
        pip install -r requirements.txt
        pip install -q .[docs]

    - name: Build docs
      run: |
        make -C docs/ html

    - name: Publish to gh-pages
      if: (github.event_name == "push" || github.event_name == "release") && ${{ !env.ACT }}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/_build/html
        CLEAN: true
